### ISSUE TITLE
Styles do not apply to reusable blocks

### ISSUE THREAD

**Issue by vena** [themeum/qubely#4]
When converting a Qubely block, for example tabs, to a reusable block, it loses styles and they don't carry over to other placements of the reusable block. This occurs with both header and filesystem style settings.

**Comment by SankarSrinivasan1** [comment]
Fahim... I am also facing the same issue. Moreover, reusable block name is also displaying over the block, at front end.

**Comment by murshed** [comment]
Hi,

Thanks for the heads up! We will inform our devs

**Comment by epakrat** [comment]
Yes, this is still an issue in the Qubely Free v1.2.1

Running WP v5.2.4 with GeneratePress Free and Gutenberg 6.8.0 on Laragon Localhost

What I did to reproduce the issue...

1) Create a Tab Block in the 'wp_block' ( Reusable Blocks Post Type). 
2) Inserted into a page from the Reusable Block Category.
3) Viewing the page produces a visible / functional ( js appears like it loaded ) but completely unstyled ( CSS didn't get enqueued?) when Tab block is output on the front end.

What fixed the issue...

I clicked the vertical 3 dots menu and selected "Convert to Regular Block" and then inserted the Reusable version again in the same page. Since the "regular" one enqueues everything proper both then display fine. If I remove the regular block (non reusable) then it fails to render correctly. Very consistent / repeatable. 

Interestingly, the CSS no longer fails after having been saved once with the "regular" version even after it has been deleted on that page and the "reusable" is the only block in the page. Is this the result of static / inline styles being saved with the content instead of dynamic? I would have expected it to revert to it's prior behavior instead of the actual behavior.

This happens regardless of the "CSS Save Method" in the options.

**Comment by nicmare** [comment]
i can confirm this!! most of the time styles to not apply. sometimes it works, sometimes not. especially when you use a reusable block which you created originally from out another page.

**Comment by anik4e** [comment]
I got the issue. You can import reusable block from here- 
http://prntscr.com/pv7mtg

Every CSS will word if you import from here. It's a temporary solution but works.

**Comment by nicmare** [comment]
No! This won't work either. Watch the complete video please:
https://www.dropbox.com/s/50k1jq5oozncm1b/reusable-block.mov?dl=0
BTW: spacing does not work too… but i like the option. Would be nice to have it on each block. Not on layouts/reusable blocks only

**Comment by anik4e** [comment]
Re-Usable block is now fixed. This bug is now testing process and added with the core ASAP.

https://github.com/themeum/qubely/commit/f4137ec0c20a959d5c483253b980a2e67b6967c6

**Comment by nicmare** [comment]
not fixed 100%. in some cases it does not work: 
https://www.dropbox.com/s/ghc8jc9n736imtt/qubely-reusable-blocks.mov?dl=0
Sometimes if you make changes to the block itself what is the main purpose of this function…

**Comment by anik4e** [comment]
We fix it again. Here is the latest build-
https://www.dropbox.com/s/x3ss3casrnmm3lm/qubely.zip?dl=0
